const NOT_FOUND_ERROR = 404;
const VALIDATION_ERROR = 400;
const BAD_REQUEST_ERROR = 400;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  NOT_FOUND_ERROR,
  VALIDATION_ERROR,
  BAD_REQUEST_ERROR,
  INTERNAL_SERVER_ERROR,
}
